Issu#60
Its-Alex/HyperTube pull request #66
Opened 2017-11-12 16:08 UTC by vacrozet

2017-11-12 16:13 UTC, Its-Alex requested changes

2017-11-12 16:13 UTC, Its-Alex commented on src/components/frontBarre.js
> +        console.log(res)
No console.log merci

2017-11-12 16:13 UTC, Its-Alex commented on src/components/frontBarre.js
> +  componentWillMount () {
Ca sert a rien de le mettre ici si tu le check a chaque fois mets le dans le state du component pas besoin de se le trimballer tout le long

2017-11-12 16:24 UTC, vacrozet commented on src/components/frontBarre.js
> +  componentWillMount () {
tu n'as pas compris le problème. Merci de te renseigner avant.
Essaye en enlevant le cwm  et tu verras que j'ai raison.

2017-11-12 17:20 UTC, vacrozet commented on src/components/frontBarre.js
> +        console.log(res)
c'est fait

2017-11-12 17:21 UTC, vacrozet commented on src/components/frontBarre.js
> +  componentWillMount () {
c'est pas fait et ce sera pas fait. j'estime que mon idée marche et qu'elle est bien, je changerais pas d'avi alors soit tu le fait soit tu acceptes. je toucherais pas à ça!

2017-11-13 09:53 UTC, Its-Alex approved these changes

2017-11-13 09:53 UTC, merged